export const HOME = '/'
export const COLLECTIONS = '/collections'
export const CLOTHES = '/clothes'
export const COLLABORATIONS = '/collaborations'
export const CHOOSE_STYLE = '/choose-style'
export const INFORMATION = '/information'

export const ACCOUNT = '/account'
export const LOGIN = '/login'
export const IMAGE = '/image'